version: "3.9"

services:

  backend:
    build: ./backend
    deploy:
      replicas: 1
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    deploy:
      replicas: 1
    ports:
      - 9000:9000
